apiVersion: v1 
kind: Service
metadata:
  name: password-api
  labels:
    app: password-api
spec:
  selector:
    app: password-api
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 3000
  type: NodePort
